name: image-build-push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      # - name: Calculate file differences
      #   id: diff
      #   uses: tj-actions/changed-files@v37
      #   with:
      #     json: true
      #     escape_json: false
      - name: Get matrix
        uses: actions/github-script@v6
        id: get-matrix
        with:
          script: |
            const { getMatrix } = await import('${{ github.workspace }}/.script/get-matrix.mjs')
            const matrix = await getMatrix('${{ github.workspace }}')
            return matrix
      - name: Build image and push
        run: echo "${{steps.get-matrix.outputs.result}}"
